### ISSUE TITLE
[FEATURE] Refactor

### ISSUE THREAD

**Issue by RasmusUK** [andreaswachs/BDSA2021-FinalProject#39]
## Describe the solution you'd like
- Two types of TagDTO:

   1. WeightedTagDTO that only exists on materials. They should consists of a TagDTO and a weight. With a foreign key to TagDTO by finding the TagDTO in the context when creating a material to the database.
   2. TagDTO to create a table of allowed tags - and expose this endpoint to the api to allow for creating, updating, removing etc. 

- Update the rating class to work like the weightedTagDTO -> A rating can only live inside a material so each rating is unique on the material itself. Also add a timestamp and comment to the rating and or maybe name of the reviever?

- Searchform:
Should the searchform just be in the form of colletions of strings instead of objects and a integer for the rating? Since we are anyway just passing the searchform to the repository that will select upon those. The search form only need the 'key' of the object and not any other thing so maybe it does not make sense to pass whole objects?

**Comment by RasmusUK** [comment]
@Myssenberg 
@AMB-F 
@andreaswachs 
@ArcanicKnight 
@ThorLL

**Comment by andreaswachs** [comment]
Your proposal sounds very good.

My own thoughts.

* On the 2nd point: Adding timestamps to ratings might be a good idea. You can argue that as a future improvement there can be metrics implemented that shows graphs ratings over time for a given material. Then this timestamp comes in handy, otherwise I don't see much point to it. It is of course important that ratings can be associated to the user who made the rating, such that we can make sure that only rating exists per material per user. Comments on ratings I'm not sure if it will be helpful for our vertical slice, but you could apply my first argument about being able to expand metrics with this kind of information. Perhaps you could look into text analysis and compute sentiment scores or what have you, in the future.

* On the 3rd point: I'm not entirely sure what we're talking about, in regards to the Searchform, but my general opinion is that if we can have concrete objects to draw information out of, instead of more "primitive" types such as strings, then I think that is the better way to go. In a perfect world we'll have unit tests to make sure that the creation and use of these objects are tested. If we're working with strings and primitive types all bets *might* be off

**Comment by RasmusUK** [comment]
There are now a new class of tags: The weightedTags which extends the normal tags.
The weighted tags are used as weak entities (Owned in EF core) and only lives upon a material with a weight.
The normal tags are used to make sure the weightedtag (name) exists in the tag table to be valid.
Authors and ratings are also now made as weak entities in the same way.
I added a timestamp and reviever to the rating.
The repository for the materials works and are tested. But the Read(SearchForm) must still be implemeted upon disuccission of the 3rd point.
