### ISSUE TITLE
[TEST] Extend materialrepository tests 

### ISSUE THREAD

**Issue by RasmusUK** [andreaswachs/BDSA2021-FinalProject#50]
## Describe the solution you'd like

Extend all test in materialRepository create, delete, update and read tests to check each returned material if it contains what is expected e.g. check that all the tags on the returned material matches what is expected etc.

**Comment by alexw-su** [comment]
A quick question considering the ReadAsync() for the TestVariable! 
If I call on the ReadAsync() for the ID value 2, am I supposed to get the materialDTO titled "Material 2" and all it's correct values?

If so, there seems to be an issue when calling ReadAsync for a specific ID that returns me a material with that has no elements in its Tags value. This happens for specifically for Material 1 and 2 but not for Material 3. 


```
[Fact]
        public async Task ReadAsync_material_by_id_returns_material_check_tags_and_status_found()
        {
            var response = await _v.MaterialRepository.ReadAsync(2);

            var actual = (response.Item1, response.Item2.Tags.First().Name, response.Item2.Tags.First().Weight);

            var expected = (Status.Found, "API", 90);

            Assert.Equal(expected, actual);
        }
```

Here is the test code I am trying to run for Material 2. 
I have not tried for the rest of the values e.g. level, rating, etc. but there seems to be no issue when accessing the title of the materials. 

edit:
Additionally, the problem seems not to happen when calling ReadAsync() without specifying an ID and all the materials have elements within their tags collections.

**Comment by RasmusUK** [comment]
Andreas is facing the same problem with his tests right where it is only the last material that actually contains anything. We will look further into this wednessday as it is a generally problem with the test data. But very nice tests. Exactly the extension we need to find these things. Keep the good work up.

It seems like that when using the same variables more than once in the test data when adding to the material. The latests material that is using a specific variable "gets" it. It cannot properly map the entities when references to the same object is used multiple places. The test data must therefor be updated accordingly.
